import React from "react";

import HeaderAndMarkDownBlock from "../HeaderAndMarkDownBlock";

export default {
  title: "BuilderComponents/HeaderAndMarkDownBlock",
  component: HeaderAndMarkDownBlock,
  argTypes: {
    bgColor: { control: "color" },
    textColor: { control: "color" },
  },
  args: {
    bgColor: "#faf6ee",
    textColor: "#264548",
    mediaPosition: "right",
    heading: "I'm the header!",
    mdContent: "**Rich** text can be found _here_.",
  },
};

const Template = args => <HeaderAndMarkDownBlock {...args} />;

export const Standard = Template.bind({});
Standard.args = {
  label: "Standard",
};
/**
 Testing to see autogenerated docs
*/
export const HeaderRight = Template.bind({});
HeaderRight.args = {
  label: "Header Right",
  /**
   Color for the background of the component
  */
  mediaPosition: "left",
};

export const Buttons = Template.bind({});
Buttons.args = {
  label: "With Buttons",
  buttons: {
    bgColor: "#faf6ee",
    fgColor: "#9de2dd",
    textColor: "#264548",
    list: [{ title: "Call to Action", content: "#" }],
  },
};
Buttons.parameters = {
  docs: {
    storyDescription:
      "Utilize the optional `button` parameter to include a call to action in this block",
  },
};
